#!/bin/bash
LOCKDIR=/var/local/cd-ripper/rip.lock
LOGFILE=/var/log/cd-ripper/status.log

function cleanup {
    if rmdir $LOCKDIR; then
        echo "Finished $(date)" | rotatelogs -e -n 5 $LOGFILE 1M
    else
        echo "Failed to remove lock dir '$LOCKDIR'" | rotatelogs -e -n 5 $LOGFILE 1M 
        exit 1
    fi
}

if mkdir $LOCKDIR; then
    trap "cleanup" EXIT
    echo "Acquired Lock, running" | rotatelogs -e -n 5 $LOGFILE 1M 
    echo "Started $(date) $$" | rotatelogs -e -n 5 $LOGFILE 1M 
    abcde -c /var/local/cd-ripper/.abcde.conf 2>&1 | rotatelogs -e -n 5 $LOGFILE 1M
    ABCDE_EXIT=$?
    echo "Stopped $(date) abcde-exited=${ABCDE_EXIT} $$" | rotatelogs -e -n 5 $LOGFILE 1M 
else
    echo "Could not create lock, already running? '$LOCKDIR'" | rotatelogs -e -n 5 $LOGFILE 1M 
    exit 1

fi